# Generated by Django 4.1 on 2022-09-02 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('compay_logo', models.ImageField(upload_to='uploads/')),
                ('team_background', models.TextField()),
                ('about_companyProducts', models.TextField()),
                ('problems', models.TextField()),
                ('uniqueSolution', models.TextField()),
                ('valueProposition', models.TextField()),
                ('competativeAdvantage', models.TextField()),
                ('revenue', models.CharField(max_length=200)),
                ('marketsize', models.CharField(max_length=200)),
                ('marketplan', models.TextField()),
                ('incubationtype', models.CharField(choices=[('Physical_Incubation', 'Physical_Incubation'), ('Virtual_Incubation ', 'Virtual_Incubation')], max_length=100)),
                ('detailProposal', models.TextField()),
                ('status', models.CharField(choices=[('Registration_Approved', 'Registration_Approved'), ('Under_Process ', 'Under_Process'), ('Approved', 'Approved')], default='Registration Approved', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
