# Generated by Django 4.1 on 2022-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Registration_pending', 'Registration_pending'), ('Registration_Under_Process ', 'Registration_Under_Process'), ('Registration_rejected', 'Registration_rejected')], max_length=100, null=True),
        ),
    ]
