# Generated by Django 4.1 on 2022-09-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_application_status_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=2, unique=True)),
                ('companyname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.application')),
            ],
        ),
    ]
