# Generated by Django 4.1 on 2022-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_application_status_boolean_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
