# Generated by Django 4.1 on 2022-09-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_slots_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status_boolean',
        ),
    ]
