# Generated by Django 4.1 on 2022-09-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_application_status_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='phone',
        ),
    ]
